const trivia = [
    "I’m not gonna run away, I never go back on my word! That’s my nindo: my ninja way!",
    "The moment you think of giving up, think of the reason why you held on so long.",
    "If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.",
    "I will become Hokage!",
    "No matter how deep the night, it always turns to day, eventually.",
    "It’s not the face that makes someone a monster; it’s the choices they make with their lives.",
    "The true measure of a shinobi is not how he lives, but how he dies.",
    "If you can’t do something, then don’t. Focus on what you can do.",
    "You should enjoy the little detours. Know where you’re going, but enjoy the ride.",
    "When you give up, your dreams and everything else, they’re gone.",
    "I’m not a hero because I want your approval. I do it because I want to!",
    "You don’t have to forgive me, but I want to be forgiven.",
    "If you’re going to die, then die! But don’t drag others down with you!",
    "I’m going to be the one who decides my destiny!",
    "A lesson without pain is meaningless. For you will not have lived.",
    "You can’t sit around envying other people’s worlds. You have to go out and change your own.",
    "The moment you think of giving up, think of the reason why you held on so long.",
    "I was always a loser. But I’m going to be Hokage, and I’m going to show everyone that I can change!",
    "You can’t bring back what you don’t have anymore. You can’t bring back the past.",
    "You should enjoy the little detours. Know where you’re going, but enjoy the ride.",
    "Whatever you lose, you’ll find it again. But what you throw away you’ll never get back.",
    "You’re not alone. You have me. You’ll always have me.",
    "I’m not going to die! I refuse to die!",
    "I want to be a hero. I want to be someone who can protect others!",
    "The reason I’m not giving up is because I have my friends to protect.",
    "A friend is someone who will always be there for you.",
    "It’s not the face that makes someone a monster; it’s the choices they make with their lives.",
    "If I’m going to die, then I’ll die fighting!",
    "Sometimes, you have to take a leap of faith to find out how far you can fly.",
    "I don’t care about being strong. I just want to be with my friends.",
    "No one knows what the future holds. That’s why its potential is infinite.",
    "I’m going to be the best ninja ever!",
    "If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.",
    "I will never go back on my word!",
    "Without a plan, nothing is possible. Don’t forget that!",
    "You can’t change the past, but you can change the future.",
    "The world isn’t perfect. But it’s there for us, doing the best it can. That’s what makes it so damn beautiful.",
    "You can’t sit around envying other people’s worlds. You have to go out and change your own.",
    "If you don’t like your destiny, don’t accept it. Instead, have the courage to change it the way you want it to be.",
    "You can’t bring back what you don’t have anymore. You can’t bring back the past.",
    "You should enjoy the little detours. Know where you’re going, but enjoy the ride.",
    "When you give up, your dreams and everything else, they’re gone.",
    "The moment you think of giving up, think of the reason why you held on so long.",
    "Even if I die, I’ll die with a smile on my face!",
    "You can’t change the past, but you can change the future.",
    "No matter how deep the night, it always turns to day, eventually.",
    "It’s not the face that makes someone a monster; it’s the choices they make with their lives.",
    "A lesson without pain is meaningless. For you will not have lived.",
    "If you’re going to die, then die! But don’t drag others down with you!",
    "I’m going to be the one who decides my destiny!",
    "A friend is someone who will always be there for you.",
    "When you give up, your dreams and everything else, they’re gone.",
    "The true measure of a shinobi is not how he lives, but how he dies.",
    "You’re not alone. You have me. You’ll always have me.",
    "If you can’t do something, then don’t. Focus on what you can do.",
    "Sometimes, you have to take a leap of faith to find out how far you can fly."
  ]
  export default trivia